import {
  collection,
  addDoc,
  getDocs,
  query,
  where,
  orderBy,
  serverTimestamp,
  doc,
  getDoc,
  updateDoc
} from 'firebase/firestore';
import { ref, uploadBytes, getDownloadURL } from 'firebase/storage';
import { db, storage } from '../firebase/config';

// ==================== STRATEGIES ====================

export const strategiesCollection = collection(db, 'strategies');

export const saveStrategy = async (data) => {
  return await addDoc(strategiesCollection, {
    businessName: data.businessName || '',
    targetAudience: data.targetAudience || '',
    businessCountry: data.businessCountry || '',
    currentMarketing: data.currentMarketing || '',
    userEmail: data.userEmail || null,
    userName: data.userName || null,
    strategy: data.strategy || {},
    marketingMaterialsLink: data.marketingMaterialsLink || '',
    marketingMaterialsFiles: data.marketingMaterialsFiles || [],
    status: data.status || 'generated', // generated, viewed, exported, emailed
    paymentStatus: data.paymentStatus || 'pending', // pending, paid, refunded
    paymentAmount: data.paymentAmount || null,
    paymentMethod: data.paymentMethod || null,
    createdAt: serverTimestamp(),
    updatedAt: serverTimestamp()
  });
};

export const getAllStrategies = async (filters = {}) => {
  let q = strategiesCollection;

  if (filters.status) {
    q = query(q, where('status', '==', filters.status));
  }

  if (filters.paymentStatus) {
    q = query(q, where('paymentStatus', '==', filters.paymentStatus));
  }

  q = query(q, orderBy('createdAt', 'desc'));

  const snapshot = await getDocs(q);
  return snapshot.docs.map(doc => ({
    id: doc.id,
    ...doc.data()
  }));
};

export const getStrategyById = async (id) => {
  const docRef = doc(db, 'strategies', id);
  const docSnap = await getDoc(docRef);
  if (docSnap.exists()) {
    return { id: docSnap.id, ...docSnap.data() };
  }
  return null;
};

export const updateStrategyStatus = async (id, data) => {
  const docRef = doc(db, 'strategies', id);
  return await updateDoc(docRef, {
    ...data,
    updatedAt: serverTimestamp()
  });
};

export const getStrategiesByUser = async (email) => {
  const q = query(
    strategiesCollection,
    where('userEmail', '==', email),
    orderBy('createdAt', 'desc')
  );
  const snapshot = await getDocs(q);
  return snapshot.docs.map(doc => ({
    id: doc.id,
    ...doc.data()
  }));
};

// ==================== STRATEGY EXPORT ====================

export const exportStrategyAsHTML = (strategyData) => {
  const { businessName, marketAnalysis, viralTrends, marketingConcepts, instagramPosts } = strategyData;

  const htmlContent = `
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>${businessName} - Strategy Roadmap</title>
  <style>
    body { font-family: 'Arial', sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; line-height: 1.6; color: #333; }
    h1 { color: #9333EA; border-bottom: 3px solid #9333EA; padding-bottom: 10px; }
    h2 { color: #9333EA; margin-top: 30px; }
    h3 { color: #6B21A8; }
    .meta { color: #666; font-size: 14px; margin-bottom: 30px; }
    .concept { background: #F3F4F6; padding: 15px; border-left: 4px solid #9333EA; margin: 15px 0; }
    .post { background: #FAFAFA; padding: 15px; border: 1px solid #E5E7EB; margin: 15px 0; }
    .trend { padding: 5px 0; }
    .footer { margin-top: 50px; padding-top: 20px; border-top: 2px solid #E5E7EB; text-align: center; color: #999; }
    ul, ol { padding-left: 20px; }
    li { margin: 8px 0; }
  </style>
</head>
<body>
  <h1>${businessName} - Strategy Roadmap</h1>
  <p class="meta">Generated on ${new Date().toLocaleDateString()} by Drift Studio</p>

  <h2>Market Analysis & Trends</h2>
  <p>${marketAnalysis}</p>
  
  <h3>Key Viral Trends:</h3>
  <ol>
    ${viralTrends.map(trend => `<li class="trend">${trend}</li>`).join('')}
  </ol>

  <h2>Marketing Concepts</h2>
  ${marketingConcepts.map((concept, i) => `
    <div class="concept">
      <h3>${i + 1}. ${concept.concept}</h3>
      <p><strong>Format:</strong> ${concept.format}</p>
      <p><strong>Hook:</strong> ${concept.hook}</p>
    </div>
  `).join('')}

  <h2>Generated Social Media Posts</h2>
  ${instagramPosts.map((post, i) => `
    <div class="post">
      <h3>Post ${i + 1}</h3>
      <p><strong>Visual Description:</strong> ${post.visual}</p>
      <p><strong>Caption:</strong></p>
      <p>${post.caption.replace(/\n/g, '<br>')}</p>
    </div>
  `).join('')}

  <div class="footer">
    <p>Generated by <strong>Drift Studio - Content Ideator</strong></p>
    <p>https://freeflowmedia.com</p>
  </div>
</body>
</html>
  `;

  const blob = new Blob([htmlContent], { type: 'text/html' });
  const url = URL.createObjectURL(blob);
  const link = document.createElement('a');
  link.href = url;
  link.download = `${businessName.replace(/\s+/g, '-')}-Strategy-Roadmap.html`;
  link.click();
  URL.revokeObjectURL(url);
};

// ==================== STRATEGY EMAIL DELIVERY ====================

export const requestStrategyDelivery = async (strategyId, userEmail) => {
  const FIREBASE_FUNCTION_URL = 'https://us-central1-freeflow-media.cloudfunctions.net/deliverStrategyViaEmail';
  
  try {
    const response = await fetch(FIREBASE_FUNCTION_URL, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        strategyId,
        userEmail
      })
    });

    if (!response.ok) {
      throw new Error('Failed to send strategy email');
    }

    return await response.json();
  } catch (error) {
    console.error('Strategy delivery failed:', error);
    throw error;
  }
};

// ==================== FILE UPLOADS ====================

export const uploadStrategyFiles = async (files) => {
  const uploadPromises = files.map(async (file) => {
    const fileRef = ref(storage, `strategies/${Date.now()}-${file.name}`);
    const snapshot = await uploadBytes(fileRef, file);
    return await getDownloadURL(snapshot.ref);
  });
  return Promise.all(uploadPromises);
};

// ==================== ANALYTICS ====================

export const getStrategyStats = async () => {
  const snapshot = await getDocs(strategiesCollection);
  const strategies = snapshot.docs.map(doc => doc.data());

  const stats = {
    total: strategies.length,
    generated: strategies.filter(s => s.status === 'generated').length,
    viewed: strategies.filter(s => s.status === 'viewed').length,
    exported: strategies.filter(s => s.status === 'exported').length,
    emailed: strategies.filter(s => s.status === 'emailed').length,
    paid: strategies.filter(s => s.paymentStatus === 'paid').length,
    pending: strategies.filter(s => s.paymentStatus === 'pending').length,
    totalRevenue: strategies
      .filter(s => s.paymentStatus === 'paid')
      .reduce((sum, s) => sum + (s.paymentAmount || 0), 0)
  };

  return stats;
};
