export const COUNTRY_CODES = [
  { code: '+27',  country: 'ZA', label: '🇿🇦 +27  South Africa' },
  { code: '+1',   country: 'US', label: '🇺🇸 +1   United States' },
  { code: '+1',   country: 'CA', label: '🇨🇦 +1   Canada' },
  { code: '+44',  country: 'GB', label: '🇬🇧 +44  United Kingdom' },
  { code: '+61',  country: 'AU', label: '🇦🇺 +61  Australia' },
  { code: '+64',  country: 'NZ', label: '🇳🇿 +64  New Zealand' },
  { code: '+49',  country: 'DE', label: '🇩🇪 +49  Germany' },
  { code: '+33',  country: 'FR', label: '🇫🇷 +33  France' },
  { code: '+31',  country: 'NL', label: '🇳🇱 +31  Netherlands' },
  { code: '+32',  country: 'BE', label: '🇧🇪 +32  Belgium' },
  { code: '+41',  country: 'CH', label: '🇨🇭 +41  Switzerland' },
  { code: '+43',  country: 'AT', label: '🇦🇹 +43  Austria' },
  { code: '+34',  country: 'ES', label: '🇪🇸 +34  Spain' },
  { code: '+39',  country: 'IT', label: '🇮🇹 +39  Italy' },
  { code: '+351', country: 'PT', label: '🇵🇹 +351 Portugal' },
  { code: '+353', country: 'IE', label: '🇮🇪 +353 Ireland' },
  { code: '+46',  country: 'SE', label: '🇸🇪 +46  Sweden' },
  { code: '+47',  country: 'NO', label: '🇳🇴 +47  Norway' },
  { code: '+45',  country: 'DK', label: '🇩🇰 +45  Denmark' },
  { code: '+358', country: 'FI', label: '🇫🇮 +358 Finland' },
  { code: '+48',  country: 'PL', label: '🇵🇱 +48  Poland' },
  { code: '+420', country: 'CZ', label: '🇨🇿 +420 Czech Republic' },
  { code: '+36',  country: 'HU', label: '🇭🇺 +36  Hungary' },
  { code: '+40',  country: 'RO', label: '🇷🇴 +40  Romania' },
  { code: '+30',  country: 'GR', label: '🇬🇷 +30  Greece' },
  { code: '+90',  country: 'TR', label: '🇹🇷 +90  Turkey' },
  { code: '+7',   country: 'RU', label: '🇷🇺 +7   Russia' },
  { code: '+380', country: 'UA', label: '🇺🇦 +380 Ukraine' },
  { code: '+971', country: 'AE', label: '🇦🇪 +971 UAE' },
  { code: '+966', country: 'SA', label: '🇸🇦 +966 Saudi Arabia' },
  { code: '+974', country: 'QA', label: '🇶🇦 +974 Qatar' },
  { code: '+965', country: 'KW', label: '🇰🇼 +965 Kuwait' },
  { code: '+973', country: 'BH', label: '🇧🇭 +973 Bahrain' },
  { code: '+968', country: 'OM', label: '🇴🇲 +968 Oman' },
  { code: '+961', country: 'LB', label: '🇱🇧 +961 Lebanon' },
  { code: '+20',  country: 'EG', label: '🇪🇬 +20  Egypt' },
  { code: '+212', country: 'MA', label: '🇲🇦 +212 Morocco' },
  { code: '+216', country: 'TN', label: '🇹🇳 +216 Tunisia' },
  { code: '+213', country: 'DZ', label: '🇩🇿 +213 Algeria' },
  { code: '+234', country: 'NG', label: '🇳🇬 +234 Nigeria' },
  { code: '+254', country: 'KE', label: '🇰🇪 +254 Kenya' },
  { code: '+233', country: 'GH', label: '🇬🇭 +233 Ghana' },
  { code: '+255', country: 'TZ', label: '🇹🇿 +255 Tanzania' },
  { code: '+256', country: 'UG', label: '🇺🇬 +256 Uganda' },
  { code: '+260', country: 'ZM', label: '🇿🇲 +260 Zambia' },
  { code: '+263', country: 'ZW', label: '🇿🇼 +263 Zimbabwe' },
  { code: '+267', country: 'BW', label: '🇧🇼 +267 Botswana' },
  { code: '+264', country: 'NA', label: '🇳🇦 +264 Namibia' },
  { code: '+268', country: 'SZ', label: '🇸🇿 +268 Eswatini' },
  { code: '+266', country: 'LS', label: '🇱🇸 +266 Lesotho' },
  { code: '+258', country: 'MZ', label: '🇲🇿 +258 Mozambique' },
  { code: '+91',  country: 'IN', label: '🇮🇳 +91  India' },
  { code: '+92',  country: 'PK', label: '🇵🇰 +92  Pakistan' },
  { code: '+94',  country: 'LK', label: '🇱🇰 +94  Sri Lanka' },
  { code: '+880', country: 'BD', label: '🇧🇩 +880 Bangladesh' },
  { code: '+86',  country: 'CN', label: '🇨🇳 +86  China' },
  { code: '+81',  country: 'JP', label: '🇯🇵 +81  Japan' },
  { code: '+82',  country: 'KR', label: '🇰🇷 +82  South Korea' },
  { code: '+65',  country: 'SG', label: '🇸🇬 +65  Singapore' },
  { code: '+60',  country: 'MY', label: '🇲🇾 +60  Malaysia' },
  { code: '+62',  country: 'ID', label: '🇮🇩 +62  Indonesia' },
  { code: '+63',  country: 'PH', label: '🇵🇭 +63  Philippines' },
  { code: '+66',  country: 'TH', label: '🇹🇭 +66  Thailand' },
  { code: '+84',  country: 'VN', label: '🇻🇳 +84  Vietnam' },
  { code: '+55',  country: 'BR', label: '🇧🇷 +55  Brazil' },
  { code: '+54',  country: 'AR', label: '🇦🇷 +54  Argentina' },
  { code: '+57',  country: 'CO', label: '🇨🇴 +57  Colombia' },
  { code: '+56',  country: 'CL', label: '🇨🇱 +56  Chile' },
  { code: '+52',  country: 'MX', label: '🇲🇽 +52  Mexico' },
];

export const DEFAULT_COUNTRY_CODE = '+27';

export const COUNTRIES = [
  'South Africa', 'Zimbabwe', 'Botswana', 'Namibia', 'Zambia', 'Mozambique',
  'Eswatini', 'Lesotho', 'Kenya', 'Tanzania', 'Uganda', 'Ghana', 'Nigeria',
  'Egypt', 'Morocco', 'United Kingdom', 'United States', 'Canada', 'Australia',
  'New Zealand', 'India', 'Singapore', 'Malaysia', 'UAE', 'Germany', 'France',
  'Netherlands', 'Brazil', 'Mexico',
];

export const SA_PROVINCES = [
  'Gauteng', 'Western Cape', 'Eastern Cape', 'KwaZulu-Natal',
  'Limpopo', 'Mpumalanga', 'North West', 'Free State', 'Northern Cape',
];

export const COUNTRY_TO_DIAL = {
  'South Africa': '+27', 'Zimbabwe': '+263', 'Botswana': '+267',
  'Namibia': '+264', 'Zambia': '+260', 'Mozambique': '+258',
  'Eswatini': '+268', 'Lesotho': '+266', 'Kenya': '+254',
  'Tanzania': '+255', 'Uganda': '+256', 'Ghana': '+233',
  'Nigeria': '+234', 'Egypt': '+20', 'Morocco': '+212',
  'United Kingdom': '+44', 'United States': '+1', 'Canada': '+1',
  'Australia': '+61', 'New Zealand': '+64', 'India': '+91',
  'Singapore': '+65', 'Malaysia': '+60', 'UAE': '+971',
  'Germany': '+49', 'France': '+33', 'Netherlands': '+31',
  'Brazil': '+55', 'Mexico': '+52',
};

// Merge dialCode + local number into a full E.164-style string
export function buildPhone(dialCode, local) {
  const clean = local.replace(/^\+?\d{1,3}[-\s]?/, '').trim();
  return clean ? `${dialCode} ${clean}` : '';
}
